export const PATHS = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    ALL_LESSONS: '/lessons',
    ALL_LESSONS: '/lessons',
    LESSON_DETAILS: '/lessons/:id',
    SUBSCRIPTION: '/pricing',
    PAYMENT_SUCCESS: '/payment/success',
    PAYMENT_FAIL: '/payment/fail',
    DASHBOARD: {
        ROOT: '/dashboard',
        ADD_LESSON: 'add-lesson',
        MY_LESSONS: 'my-lessons',
        MY_FAVORITES: 'my-favorites',
        PROFILE: 'profile',
        UPDATE_LESSON: 'update-lesson/:id',
    },
    ADMIN: {
        ROOT: 'admin',
        DASHBOARD: 'home',
        MANAGE_USERS: 'manage-users',
        MANAGE_LESSONS: 'manage-lessons',
        REPORTED_LESSONS: 'reported-lessons',
        PROFILE: 'profile',
    },
};
